### ISSUE TITLE
Question on Distributed training

### ISSUE THREAD

**Issue by wtam** [DLTK/DLTK#23]
I'm trying to run one of the DLTK sample on 3 nodes Distributed Training but get stuck at 
nn.train( input_fn=train_input_fn,
               hooks=[train_qinit_hook, step_cnt_hook],
                steps=EVAL_EVERY_N_STEPS)
forever and without any error.  Would anyone has idea or something I missed?

My cluster spec is like this and I've ps, chief, and worker tasktype defined correctly
TF_CONFIG:  {"cluster": {"ps": ["10.0.0.5:2222"], "chief": ["10.0.0.5:2223"], "worker": ["10.0.0.6:2222", "10.0.0.4:2222"]}, "task": {"type": "ps", "index": 0}, "environment": "cloud"}

**Comment by mrajchl** [comment]
Hi there,
we haven't tested DLTK examples in a distributed setup. According to the tf docs (https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate), it should be feasible.

However, the only component that might pose an issue in distributed training might be the reader. Have you tried generating a different input function (just generating noise inputs) instead of the DLTK data reader (https://github.com/DLTK/DLTK/blob/master/examples/applications/MRBrainS13_tissue_segmentation/train.py#L145)? This would determine where the problem is. 

I'll keep this issue open, as this issue might be due to a bug in the DLTK reader. You could also try and see if a pure tf estimator example runs with your config or check out T2T (https://github.com/tensorflow/tensor2tensor/blob/master/docs/distributed_training.md)
