### ISSUE TITLE
Image and label shape must match in extract_class_balanced_example_array()

### ISSUE THREAD

**Issue by pldelisle** [DLTK/DLTK#34]
Hi, 

I'm experiencing an issue with the balanced sampler.

Full image (NumPy array) is shape (130, 164, 145, 1). Segmentation is identical. 

If we look at the source code of the function, it seems it fails on the first assert. 

My goal was to use this function to get a balanced set of 3D patches of shape (64, 64, 64). Is it possible ?

Thanks,

Pierre-Luc

**Comment by mrajchl** [comment]
Hi Pierre-Luc, 
yes it is of course possible. You fail the asserts, because the the labels should be of size (130, 164, 145) and or not yet one-hot encoded. Please refer to our tutorial application on segmentation: https://github.com/DLTK/DLTK/blob/master/examples/applications/MRBrainS13_tissue_segmentation/reader.py#L80

I'll close this for now, as this is no bug. If you require help please chat with us in our gitter chat (button in the readme)

**Comment by pldelisle** [comment]
Thank you very much. 

After analyzing the tutorial app, I realized I needed to transpose the channels of my image data to channel_last and reduce the dimension of the labels.  It now works like a charm.

Thanks a lot !
