### ISSUE TITLE
Error while training with different number of filters

### ISSUE THREAD

**Issue by npardakhti** [DLTK/DLTK#39]
I'm using DLTK package. In the path 
DLTK-master\examples\applications\IXI_HH_age_regression_resnet, the train.py got errors. I have resized the images to 64*64*64, and just decreased the filters to filters=(8, 16, 32), (instead of (16, 32, 64, 128, 256)). Also, I changed the resnet.py parameters to match with the parameters in train.py. 

But I have got this error:

Assign requires shapes of both tensors to match. lhs shape= [3,3,3,1,8] rhs shape= [3,3,3,1,16]
	 [[node save/Assign_2 (defined at E:/UT Projects/khanom Dr.Sajedi/DLTK-master/examples/applications/IXI_HH_age_regression_resnet/train.py:191)  = Assign[T=DT_FLOAT, _class=["loc:@conv3d/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv3d/kernel, save/RestoreV2:2)]]

Assign requires shapes of both tensors to match. lhs shape= [3,3,3,1,8] rhs shape= [3,3,3,1,16]
	 [[node save/Assign_2 (defined at E:/UT Projects/khanom Dr.Sajedi/DLTK-master/examples/applications/IXI_HH_age_regression_resnet/train.py:191)  = Assign[T=DT_FLOAT, _class=["loc:@conv3d/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv3d/kernel, save/RestoreV2:2)]]

I don't know what is wrong with the tensor shapes. Would anyone help me please?

**Comment by mrajchl** [comment]
Hi @npardakhti,
apologies for the late reply. The reason you are getting this error is, because you did set the --restart flag. Because of this, the network tried to continue reading from the old model output folder and the shapes of the weights it found were not those that you were specifying in the code. 

Closed, as this is not a bug of DLTK, but a feature of tensorflow
